import type { Product } from "@/types";

export const fruits: Product[] = [
  {
    id: "fruit-001",
    name: "Classic Fruit Box",
    description: "A handpicked selection of 12 seasonal fruits — apples, pears, bananas, citrus & berries. Perfect for a team of 5–8.",
    price: 34.9,
    subscriptionPrices: { weekly: 29.9, biweekly: 31.9, monthly: 32.9 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&q=80",
    badges: ["Bestseller", "Team Favourite"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 218,
    inStock: true,
  },
  {
    id: "fruit-002",
    name: "Seasonal Harvest Box",
    description: "Curated around what's perfectly ripe right now. Sourced from Swiss & nearby farms, changes every week.",
    price: 38.5,
    subscriptionPrices: { weekly: 33.0, biweekly: 35.0, monthly: 36.5 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=80",
    badges: ["Seasonal", "Local"],
    dietaryTags: ["vegan", "organic"],
    seasonal: true,
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
  },
  {
    id: "fruit-003",
    name: "Exotic Fruit Box",
    description: "Mangoes, papayas, dragon fruit, passion fruit & lychees. Bring the tropics to your office.",
    price: 54.0,
    subscriptionPrices: { weekly: 48.0, biweekly: 50.0, monthly: 52.0 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=600&q=80",
    badges: ["Premium", "Popular"],
    dietaryTags: ["vegan"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
  },
  {
    id: "fruit-004",
    name: "Mini Snack Box",
    description: "Individual snack packs — small teams or hot desks. Clementines, grapes, plums & cherry tomatoes.",
    price: 22.0,
    subscriptionPrices: { weekly: 18.5, biweekly: 19.5, monthly: 20.5 },
    category: "fruits",
    subcategory: "snacks",
    image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&q=80",
    badges: ["Light", "Healthy"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: "fruit-005",
    name: "Large Office Box",
    description: "30+ pieces of mixed fruits for teams of 15–25. Guaranteed freshness, delivered before 8am.",
    price: 72.0,
    subscriptionPrices: { weekly: 64.0, biweekly: 66.0, monthly: 68.0 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80",
    badges: ["Large Team", "Value"],
    dietaryTags: ["vegan"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
  },
  {
    id: "fruit-006",
    name: "Berry Lovers Box",
    description: "Strawberries, raspberries, blueberries, blackberries — antioxidant-packed office treat.",
    price: 42.0,
    subscriptionPrices: { weekly: 37.0, biweekly: 39.0, monthly: 40.5 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=600&q=80",
    badges: ["Seasonal", "Antioxidant"],
    dietaryTags: ["vegan", "organic"],
    seasonal: true,
    rating: 4.9,
    reviewCount: 76,
    inStock: false,
  },
];

export const cateringItems: Product[] = [
  {
    id: "cat-001",
    name: "Croissant Basket",
    description: "Freshly baked butter croissants, pain au chocolat & almond twists. Min. 10 pcs.",
    price: 38.0,
    subscriptionPrices: { weekly: 32.0, biweekly: 34.0, monthly: 36.0 },
    category: "catering",
    subcategory: "pastries",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    badges: ["Fresh Baked", "Popular"],
    dietaryTags: ["vegetarian"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    minQuantity: 10,
  },
  {
    id: "cat-002",
    name: "Power Grain Bowl",
    description: "Quinoa, roasted veggies, avocado, edamame & tahini dressing. Individually portioned.",
    price: 14.5,
    subscriptionPrices: { weekly: 12.5, biweekly: 13.0, monthly: 13.5 },
    category: "catering",
    subcategory: "bowls",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    badges: ["Vegan", "High Protein"],
    dietaryTags: ["vegan", "gluten-free"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: "cat-003",
    name: "Cold Brew Coffee Box",
    description: "12 × 250ml cold brew coffee cans. Smooth, low-acid, ready to drink.",
    price: 36.0,
    subscriptionPrices: { weekly: 30.0, biweekly: 32.0, monthly: 33.0 },
    category: "catering",
    subcategory: "drinks",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
    badges: ["Refreshing", "Caffeine Boost"],
    dietaryTags: ["vegan", "dairy-free"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 155,
    inStock: true,
  },
  {
    id: "cat-004",
    name: "Swiss Cheese & Charcuterie Platter",
    description: "Raclette, Appenzeller, Gruyère with cured meats, cornichons & artisan crackers.",
    price: 89.0,
    subscriptionPrices: { weekly: 78.0, biweekly: 82.0, monthly: 85.0 },
    category: "catering",
    subcategory: "platters",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",
    badges: ["Premium", "Meeting Ready"],
    dietaryTags: ["gluten-free"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
  },
  {
    id: "cat-005",
    name: "Mini Sandwich Selection",
    description: "12 gourmet mini sandwiches — smoked salmon, caprese & turkey pesto on artisan bread.",
    price: 54.0,
    subscriptionPrices: { weekly: 46.0, biweekly: 49.0, monthly: 51.0 },
    category: "catering",
    subcategory: "pastries",
    image: "https://images.unsplash.com/photo-1604467794349-0b74285de7e7?w=600&q=80",
    badges: ["Crowd Pleaser", "Lunch"],
    dietaryTags: ["dairy-free"],
    seasonal: false,
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
  },
  {
    id: "cat-006",
    name: "Kombucha & Juice Pack",
    description: "8 × kombucha + 4 × cold-pressed juice. Energising, gut-healthy office drinks.",
    price: 44.0,
    subscriptionPrices: { weekly: 37.0, biweekly: 39.5, monthly: 41.0 },
    category: "catering",
    subcategory: "drinks",
    image: "https://images.unsplash.com/photo-1622484212850-eb596d769edc?w=600&q=80",
    badges: ["Probiotic", "Natural"],
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 92,
    inStock: true,
  },
];

export const giftItems: Product[] = [
  {
    id: "gift-001",
    name: "Wellness Gift Box",
    description: "Premium fruit selection + herbal teas + artisan dark chocolate. Ready to brand with your logo.",
    price: 68.0,
    subscriptionPrices: { weekly: 60.0, biweekly: 63.0, monthly: 65.0 },
    category: "gifts",
    subcategory: "wellness",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80",
    badges: ["Bestseller", "Brandable"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 241,
    inStock: true,
    minQuantity: 5,
  },
  {
    id: "gift-002",
    name: "Gourmet Treat Box",
    description: "Swiss chocolate, premium nuts, dried fruits & artisan biscuits. Elegantly wrapped.",
    price: 84.0,
    subscriptionPrices: { weekly: 74.0, biweekly: 78.0, monthly: 80.0 },
    category: "gifts",
    subcategory: "gourmet",
    image: "https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=600&q=80",
    badges: ["Premium", "Luxury"],
    dietaryTags: ["vegetarian"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    minQuantity: 5,
  },
  {
    id: "gift-003",
    name: "Seasonal Hamper",
    description: "Festive seasonal produce + local honey + handmade jam. Changes with the seasons.",
    price: 95.0,
    subscriptionPrices: { weekly: 84.0, biweekly: 88.0, monthly: 91.0 },
    category: "gifts",
    subcategory: "hampers",
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600&q=80",
    badges: ["Seasonal", "Artisan"],
    dietaryTags: ["vegetarian", "organic"],
    seasonal: true,
    rating: 4.9,
    reviewCount: 98,
    inStock: true,
    minQuantity: 3,
  },
];

export const testimonials = [
  {
    id: "t-001",
    quote: "Our team looks forward to Monday mornings now — the fruit box is the first thing everyone grabs. Delivery is always on time and the quality is exceptional.",
    author: "Sarah Müller",
    role: "Office Manager",
    company: "Zurich Financial Group",
    avatar: "",
  },
  {
    id: "t-002",
    quote: "We switched to GreenCrate for all our client meetings. The catering platters are stunning and the team always gets compliments. Absolutely worth every franc.",
    author: "Marco Bernasconi",
    role: "Head of Operations",
    company: "Helvetia Tech",
    avatar: "",
  },
  {
    id: "t-003",
    quote: "The corporate gift boxes with our logo were a huge hit at our year-end event. Clients loved them. Will definitely order again.",
    author: "Lena Vogt",
    role: "Marketing Director",
    company: "Alpine Ventures",
    avatar: "",
  },
];

export const allProducts = [...fruits, ...cateringItems, ...giftItems];
