import type { Product } from "@/types";

export const fruits: Product[] = [
  {
    id: "fruit-001",
    name: "Classic Fruit Box",
    description: "A handpicked selection of 12 seasonal fruits — Rajshahi mangoes, local bananas, citrus & berries. Perfect for a team of 5–8.",
    price: 3490,
    subscriptionPrices: { weekly: 2990, biweekly: 3190, monthly: 3290 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&q=80",
    badges: ["Bestseller", "Team Favourite"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 218,
    inStock: true,
  },
  {
    id: "fruit-002",
    name: "Seasonal Harvest Box",
    description: "Curated around what's perfectly ripe right now. Sourced from local Bangladeshi farms in Sylhet & North Bengal.",
    price: 3850,
    subscriptionPrices: { weekly: 3300, biweekly: 3500, monthly: 3650 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=80",
    badges: ["Seasonal", "Local"],
    dietaryTags: ["vegan", "organic"],
    seasonal: true,
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
  },
  {
    id: "fruit-003",
    name: "Tropical Exotic Box",
    description: "Local mangoes, papayas, dragon fruit, lychees & jackfruit. The best of Bangladesh for your office.",
    price: 5400,
    subscriptionPrices: { weekly: 4800, biweekly: 5000, monthly: 5200 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=600&q=80",
    badges: ["Premium", "Popular"],
    dietaryTags: ["vegan"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
  },
  {
    id: "fruit-004",
    name: "Office Snack Pack",
    description: "Individual snack packs — small teams or hot desks. Guavas, plums, grapes & local clementines.",
    price: 2200,
    subscriptionPrices: { weekly: 1850, biweekly: 1950, monthly: 2050 },
    category: "fruits",
    subcategory: "snacks",
    image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&q=80",
    badges: ["Light", "Healthy"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: "fruit-005",
    name: "Corporate Mega Box",
    description: "30+ pieces of mixed fruits for teams of 15–25. Guaranteed freshness, delivered before 8am.",
    price: 7200,
    subscriptionPrices: { weekly: 6400, biweekly: 6600, monthly: 6800 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80",
    badges: ["Large Team", "Value"],
    dietaryTags: ["vegan"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
  },
  {
    id: "fruit-006",
    name: "Lychee & Berry Treat",
    description: "Fresh Dinajpur lychees, strawberries, and local seasonal berries — antioxidant-packed office treat.",
    price: 4200,
    subscriptionPrices: { weekly: 3700, biweekly: 3900, monthly: 4050 },
    category: "fruits",
    subcategory: "boxes",
    image: "https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?w=600&q=80",
    badges: ["Seasonal", "Antioxidant"],
    dietaryTags: ["vegan", "organic"],
    seasonal: true,
    rating: 4.9,
    reviewCount: 76,
    inStock: false,
  },
];

export const cateringItems: Product[] = [
  {
    id: "cat-001",
    name: "Artisan Pastry Basket",
    description: "Freshly baked butter croissants, local style sweet buns & almond twists. Min. 10 pcs.",
    price: 3800,
    subscriptionPrices: { weekly: 3200, biweekly: 3400, monthly: 3600 },
    category: "catering",
    subcategory: "pastries",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    badges: ["Fresh Baked", "Popular"],
    dietaryTags: ["vegetarian"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    minQuantity: 10,
  },
  {
    id: "cat-002",
    name: "Power Grain Bowl",
    description: "Local grains, roasted seasonal veggies, avocado & tahini dressing. Individually portioned.",
    price: 1450,
    subscriptionPrices: { weekly: 1250, biweekly: 1300, monthly: 1350 },
    category: "catering",
    subcategory: "bowls",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    badges: ["Vegan", "High Protein"],
    dietaryTags: ["vegan", "gluten-free"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: "cat-003",
    name: "Artisan Coffee Box",
    description: "12 × 250ml cold brew coffee cans using local beans. Smooth, low-acid, ready to drink.",
    price: 3600,
    subscriptionPrices: { weekly: 3000, biweekly: 3200, monthly: 3300 },
    category: "catering",
    subcategory: "drinks",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
    badges: ["Refreshing", "Caffeine Boost"],
    dietaryTags: ["vegan", "dairy-free"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 155,
    inStock: true,
  },
  {
    id: "cat-004",
    name: "Local Artisan Cheese Platter",
    description: "Selection of local artisan cheeses with cured meats, chutneys & handmade crackers.",
    price: 8900,
    subscriptionPrices: { weekly: 7800, biweekly: 8200, monthly: 8500 },
    category: "catering",
    subcategory: "platters",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80",
    badges: ["Premium", "Meeting Ready"],
    dietaryTags: ["gluten-free"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
  },
  {
    id: "cat-005",
    name: "Gourmet Sandwich Mix",
    description: "12 gourmet mini sandwiches — spiced chicken, caprese & turkey pesto on local artisan bread.",
    price: 5400,
    subscriptionPrices: { weekly: 4600, biweekly: 4900, monthly: 5100 },
    category: "catering",
    subcategory: "pastries",
    image: "https://images.unsplash.com/photo-1604467794349-0b74285de7e7?w=600&q=80",
    badges: ["Crowd Pleaser", "Lunch"],
    dietaryTags: ["dairy-free"],
    seasonal: false,
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
  },
  {
    id: "cat-006",
    name: "Kombucha & Fresh Juice Pack",
    description: "8 × kombucha + 4 × cold-pressed local fruit juice. Energising, gut-healthy office drinks.",
    price: 4400,
    subscriptionPrices: { weekly: 3700, biweekly: 3950, monthly: 4100 },
    category: "catering",
    subcategory: "drinks",
    image: "https://images.unsplash.com/photo-1622484212850-eb596d769edc?w=600&q=80",
    badges: ["Probiotic", "Natural"],
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    seasonal: false,
    rating: 4.7,
    reviewCount: 92,
    inStock: true,
  },
  {
    id: "cat-007",
    name: "Vegan Power Lunchbag",
    description: "Grain bowl + green juice + raw energy ball. The perfect healthy desk lunch.",
    price: 2450,
    subscriptionPrices: { weekly: 2100, biweekly: 2250, monthly: 2350 },
    category: "catering",
    subcategory: "lunchbags",
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
    badges: ["Best Value", "Vegan"],
    dietaryTags: ["vegan", "gluten-free"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
  },
  {
    id: "cat-008",
    name: "Dhaka Executive Lunchbag",
    description: "Premium sandwich + seasonal fruit + local sweets + mineral water.",
    price: 1950,
    subscriptionPrices: { weekly: 1650, biweekly: 1750, monthly: 1850 },
    category: "catering",
    subcategory: "lunchbags",
    image: "https://images.unsplash.com/photo-1540331547168-8b63109225b7?w=600&q=80",
    badges: ["Popular"],
    dietaryTags: ["vegetarian"],
    seasonal: false,
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
  },
];

export const giftItems: Product[] = [
  {
    id: "gift-001",
    name: "Wellness Gift Box",
    description: "Premium fruit selection + local organic teas + artisan dark chocolate. Ready to brand with your logo.",
    price: 6800,
    subscriptionPrices: { weekly: 6000, biweekly: 6300, monthly: 6500 },
    category: "gifts",
    subcategory: "wellness",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80",
    badges: ["Bestseller", "Brandable"],
    dietaryTags: ["vegan", "organic"],
    seasonal: false,
    rating: 4.9,
    reviewCount: 241,
    inStock: true,
    minQuantity: 5,
  },
  {
    id: "gift-002",
    name: "Gourmet Treat Box",
    description: "Premium local sweets, artisan nuts, dried fruits & handmade biscuits. Elegantly wrapped.",
    price: 8400,
    subscriptionPrices: { weekly: 7400, biweekly: 7800, monthly: 8000 },
    category: "gifts",
    subcategory: "gourmet",
    image: "https://images.unsplash.com/photo-1549007953-2f2dc0b24019?w=600&q=80",
    badges: ["Premium", "Luxury"],
    dietaryTags: ["vegetarian"],
    seasonal: false,
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    minQuantity: 5,
  },
  {
    id: "gift-003",
    name: "Seasonal Hamper",
    description: "Festive seasonal produce + local organic honey + handmade jam. Changes with the seasons.",
    price: 9500,
    subscriptionPrices: { weekly: 8400, biweekly: 8800, monthly: 9100 },
    category: "gifts",
    subcategory: "hampers",
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600&q=80",
    badges: ["Seasonal", "Artisan"],
    dietaryTags: ["vegetarian", "organic"],
    seasonal: true,
    rating: 4.9,
    reviewCount: 98,
    inStock: true,
    minQuantity: 3,
  },
];

export const testimonials = [
  {
    id: "t-001",
    quote: "Our team looks forward to Sunday mornings now — the fruit box is the first thing everyone grabs. Delivery is always on time and the quality is exceptional.",
    author: "Arif Ahmed",
    role: "Office Manager",
    company: "Grameenphone",
    avatar: "",
  },
  {
    id: "t-002",
    quote: "We switched to GreenCrate for all our client meetings. The catering platters are stunning and the team always gets compliments. Absolutely worth every taka.",
    author: "Nabila Chowdhury",
    role: "Head of Operations",
    company: "Pathao",
    avatar: "",
  },
  {
    id: "t-003",
    quote: "The corporate gift boxes with our logo were a huge hit at our year-end event. Clients loved them. Will definitely order again.",
    author: "Tanvir Khan",
    role: "Marketing Director",
    company: "BRAC",
    avatar: "",
  },
];

export const allProducts = [...fruits, ...cateringItems, ...giftItems];
